### ISSUE TITLE
Help with import csep

### ISSUE THREAD

**Issue by sbaccari** [SCECcode/pycsep#177]
Hi, I have problem with import the library csep in python:
when I write import csep, I obtain this response from interpeter. Can you give me a suggestion? Thanks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sbaccari/pycsep/csep/__init__.py", line 7, in <module>
    from csep.core import forecasts
  File "/home/sbaccari/pycsep/csep/core/forecasts.py", line 14, in <module>
    from csep.core.catalogs import AbstractBaseCatalog
  File "/home/sbaccari/pycsep/csep/core/catalogs.py", line 18, in <module>
    from csep.utils.comcat import SummaryEvent
  File "/home/sbaccari/pycsep/csep/utils/comcat.py", line 19, in <module>
    from obspy.core.event import read_events
  File "/home/sbaccari/miniconda3/envs/csep-dev/lib/python3.10/site-packages/obspy/__init__.py", line 39, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/home/sbaccari/miniconda3/envs/csep-dev/lib/python3.10/site-packages/obspy/core/__init__.py", line 124, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/home/sbaccari/miniconda3/envs/csep-dev/lib/python3.10/site-packages/obspy/core/utcdatetime.py", line 27, in <module>
    from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
  File "/home/sbaccari/miniconda3/envs/csep-dev/lib/python3.10/site-packages/obspy/core/util/__init__.py", line 27, in <module>
    from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
  File "/home/sbaccari/miniconda3/envs/csep-dev/lib/python3.10/site-packages/obspy/core/util/base.py", line 36, in <module>
    from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
  File "/home/sbaccari/miniconda3/envs/csep-dev/lib/python3.10/site-packages/obspy/core/util/misc.py", line 214, in <module>
    loadtxt(np.array([0]), ndmin=1)
  File "/home/sbaccari/miniconda3/envs/csep-dev/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1086, in loadtxt
    ncols = len(usecols or split_line(first_line))
  File "/home/sbaccari/miniconda3/envs/csep-dev/lib/python3.10/site-packages/numpy/lib/npyio.py", line 977, in split_line
    line = line.split(comment, 1)[0]
AttributeError: 'numpy.int64' object has no attribute 'split'
is:issue is:open 'numpy.int64' object has no attribute 'split'

**Comment by wsavran** [comment]
Hi @sbaccari! This appears to be related to #168. I'm releasing a new version today that fixes this issue. In the meantime, a workaround would be to install the correct version of numpy first and then pycsep.
```
conda install --channel conda-forge numpy=1.21.5 pycsep
```

**Comment by wsavran** [comment]
@sbaccari i created a new release of pycsep that has pinned versions that should fix this issue. let me know if running 
```
conda install --channel conda-forge pycsep
```
works as expected.
